# Image for Clean up the whole stack
FROM ubuntu:18.04

USER root

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y install tzdata && \
    apt-get -y install unzip curl jq wget

# Install awscli and lightsail plugin
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl" && \
    chmod +x /usr/local/bin/lightsailctl

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip
RUN unzip terraform_1.0.4_linux_amd64.zip && rm terraform_1.0.4_linux_amd64.zip
RUN mv terraform /usr/bin/terraform

COPY clean.sh .
RUN chmod +x clean.sh

CMD ["./clean.sh"]